#!/usr/bin/env bash
#script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

for ((i=0; i < 10; i++))
do
	if [ $i -eq 8 ]
		then
			echo "Best School"
			echo "Hi"
	else
		echo "Best School"
	fi
done
